[project]
name = "monitor-campista"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "adbc-driver-sqlite>=1.8.0",
    "duckdb>=1.4.0",
    "jupyterlab>=4.4.7",
    "polars>=1.33.1",
    "streamlit>=1.50.0",
]
