[theme]

font = "EB Garamond"
headingFont = "EB Garamond"

# ------------------------------------------------------------------
#  FLEXOKI  –  https://github.com/kepano/flexoki
# ------------------------------------------------------------------

# 1. Core brand switch -------------------------------------------------
base = "light"

# 2. Surfaces ----------------------------------------------------------
backgroundColor             = "#FFFFFF"   # pure white – main canvas
secondaryBackgroundColor    = "#F2EFE6"   # paper-100 – sidebar, cards, tooltips

# 3. Ink ----------------------------------------------------------------
textColor                   = "#100F0F"   # ink-900   – highest contrast body text
# (Streamlit derives muted text automatically at 80 % opacity of textColor)

# 4. Accent & interaction ---------------------------------------------
primaryColor                = "#8a9a48"   #           – buttons, checkboxes, sliders
linkColor                   = "#007F77"   # same as primary for consistency

# 5. Boundaries --------------------------------------------------------
borderColor                 = "#CFCDC4"   # paper-200 – subtle dividers
# Keep border thin (1 px) in st.markdown CSS for airy feel.
dataframeBorderColor =   "#FFFCF0"


colorScale = [
    "#8a9a48",
    "#007F77",   # teal-700  – accent, starts the scale
    "#4385BE",   # blue-600
    "#8B7EC8",   # purple-600
    "#D83232",   # red-700
    "#BC6F00",   # orange-700
    "#6F6E69"    # gray-600  – neutral end-stop
]
